### ISSUE TITLE
I think your archive job always uploads yesterday‘s screenshot

### ISSUE THREAD

**Issue by Jwhiles** [spencerc99/spencer-net-shots#1]
I like the idea of archiving your site everyday, and so I copied your action code. I realised that it actually upload yesterdays screenshot. (I only spotted this cos I had changed the page being screenshotted today).

The reason this happens is that actions are run on a specific commit, so even though the first job pushes an updated version of the repo, when the second job checks out the repo, it's still fetching the old commit.

I got around this by storing the screenshot as an artifact, you can see the change in [this commit](https://github.com/Jwhiles/johncom-screen-shotter/commit/3a3b2788f6f635eab8cd284dc19d8e99c0cd3c4e) in case you want to make the same change here.

**Comment by spencerc99** [comment]
> I like the idea of archiving your site everyday, and so I copied your action code. I realised that it actually upload yesterdays screenshot. (I only spotted this cos I had changed the page being screenshotted today).
> 
> The reason this happens is that actions are run on a specific commit, so even though the first job pushes an updated version of the repo, when the second job checks out the repo, it's still fetching the old commit.
> 
> I got around this by storing the screenshot as an artifact, you can see the change in [this commit](https://github.com/Jwhiles/johncom-screen-shotter/commit/3a3b2788f6f635eab8cd284dc19d8e99c0cd3c4e) in case you want to make the same change here.

ahhh yeah I just made amends with it since it would eventually get everything haha. thank you for figuring out how to do it by avoiding checking out the repo entirely! gonna integrate this :) hope you enjoy your archive of website screenshots

**Comment by spencerc99** [comment]
i had also wanted to make it so it just commits every new photo to the repo (folder per side, with date as the name) rather than to s3.. you inspired me with this issue to try to get that working again but alas still seems unsupported (https://github.com/simonw/shot-scraper/issues/130). if this is interesting to you and you figure it out let me know haha

**Comment by Jwhiles** [comment]
I don't know enough python to be able to do this in a ”nice“ way. But I think you can do it with github actions relatively easily.

You could re-use the code you already have in the action to generate the file name, rename the file after the screenshot is created, and then the step that commits and pushes to the repo will handle everything else.

[I tried this on my repo and it seems to work](https://github.com/Jwhiles/johncom-screen-shotter/commit/092498b0e802803eb51a38e143f11d579005844d#diff-76ff913ccd1623c0f142ffc4232b8700267a292114ff8763bf0b59f019b39a3fR58-R67) - yours would be a bit different because you have two screenshots - but I think you'd just need to add another `mv` :)

**Comment by spencerc99** [comment]
oh yeah ur a genius LOL updated it to do that :) thanks for the help

**Comment by Jwhiles** [comment]
Nice! Glad that it's all working, and once again thanks for the idea  - I'm just sad I didn't start this 5 years ago 😄
